name: CI
on:
  push:
    branches: [ "main", "IT*" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build API
        run: dotnet build ./velocart-system.API/velocart-system.API.csproj
